import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext"; // Import your AuthProvider
import { ApplicationProvider } from "@/contexts/applicationContext";
import { InternshipProvider } from "@/contexts/internshipContext";
import { JobProvider } from "@/contexts/jobContext";
import { StorageProvider } from "@/contexts/storageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Campus2Career",
  description: "Generated by Campus2Career",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ApplicationProvider>
            <InternshipProvider>
              <JobProvider>
                <StorageProvider>
                  {children}
                </StorageProvider>
              </JobProvider>
            </InternshipProvider>
          </ApplicationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}