import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Corrected import
import "./globals.css";

import { AuthProvider } from "../contexts/AuthContext";
import { ApplicationProvider } from "@/contexts/applicationContext";
import { InternshipProvider } from "@/contexts/internshipContext";
import { JobProvider } from "@/contexts/jobContext";
import { StorageProvider } from "@/contexts/storageContext";
import { OfferProvider } from "@/contexts/offerContext";
import { ReviewProvider } from "@/contexts/reviewContext";
import { NotificationProvider } from "@/contexts/notificationContext";
import { MessagingProvider } from "@/contexts/messagingContext";

import ClientRootLayout from "./Components/ClientRootLayout";

// Use default imports for fonts
const geistSans = Geist({
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "CareerXHub",
  description: "Generated by Campus2Career",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className} antialiased`}>
        <AuthProvider>
          <ApplicationProvider>
            <InternshipProvider>
              <JobProvider>
                <StorageProvider>
                  <OfferProvider>
                    <ReviewProvider>
                      <NotificationProvider>
                        <MessagingProvider>
                          <ClientRootLayout>{children}</ClientRootLayout>
                        </MessagingProvider>
                      </NotificationProvider>
                    </ReviewProvider>
                  </OfferProvider>
                </StorageProvider>
              </JobProvider>
            </InternshipProvider>
          </ApplicationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
