import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "../contexts/AuthContext";
import { ApplicationProvider } from "@/contexts/applicationContext";
import { InternshipProvider } from "@/contexts/internshipContext";
import { JobProvider } from "@/contexts/jobContext";
import { StorageProvider } from "@/contexts/storageContext";
import { OfferProvider } from "@/contexts/offerContext";
import { ReviewProvider } from "@/contexts/reviewContext";
import ClientWrapper from "@/app/Components/ClientWrapper";
import { NotificationProvider } from "@/contexts/notificationContext";
import { MessagingProvider } from "@/contexts/messagingContext";
import NotificationToast from "./Components/NotificationToast";
import NotificationDemo from "./Components/NotificationDemo";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CareerXHub",
  description: "Generated by Campus2Career",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <ApplicationProvider>
            <InternshipProvider>
              <JobProvider>
                <StorageProvider>
                  <OfferProvider>
                    <ReviewProvider>
                      <ClientWrapper>                      
                        <NotificationProvider>
                          <MessagingProvider>
                            {children}
                            <NotificationToast />
                            <NotificationDemo />
                          </MessagingProvider>
                        </NotificationProvider>
                      </ClientWrapper>
                    </ReviewProvider>
                  </OfferProvider>
                </StorageProvider>
              </JobProvider>
            </InternshipProvider>
          </ApplicationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}